/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Hlava: THREE.Mesh
    Brada: THREE.Mesh
    Hair_Path001: THREE.Mesh
    Hair_Path002: THREE.Mesh
    Hair_Path003: THREE.Mesh
    Hair_Path004: THREE.Mesh
    Hair_Path005: THREE.Mesh
    Hair_Path006: THREE.Mesh
    Hair_Path007: THREE.Mesh
    Hair_Path008: THREE.Mesh
    Hair_Path009: THREE.Mesh
    Hair_Path010: THREE.Mesh
    Hair_Path011: THREE.Mesh
    Hair_Path012: THREE.Mesh
    Hair_Path013: THREE.Mesh
    Hair_Path014: THREE.Mesh
    Hair_Path015: THREE.Mesh
    Hair_Path017: THREE.Mesh
    Hair_Path018: THREE.Mesh
    Hair_Path019: THREE.Mesh
    Hair_Path020: THREE.Mesh
    Hair_Path021: THREE.Mesh
    Hair_Path022: THREE.Mesh
    Hair_Path023: THREE.Mesh
    Hair_Path024: THREE.Mesh
    Hair_Path025: THREE.Mesh
    Hair_Path026: THREE.Mesh
    Hair_Path027: THREE.Mesh
    Eyebrows_Path002: THREE.Mesh
    Eyebrows_Path003: THREE.Mesh
    Eyebrows_Path004: THREE.Mesh
    Eyebrows_Path005: THREE.Mesh
    Eyebrows_Path006: THREE.Mesh
    Eyebrows_Path007: THREE.Mesh
    Eyebrows_Path008: THREE.Mesh
    Eyebrows_Path009: THREE.Mesh
    Eyebrows_Path010: THREE.Mesh
    Eyebrows_Path011: THREE.Mesh
    Telo_bez_hlavy: THREE.Mesh
  }
  materials: {
    CLAY_Telo: THREE.MeshStandardMaterial
  }
}

export function SelfCharacter3DModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Self-character-compressed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Hlava.geometry} material={materials.CLAY_Telo} position={[-0.034, 1.558, -0.21]} rotation={[0.02, 0.197, -0.101]} scale={[0.105, 0.107, 0.105]} />
      <mesh castShadow receiveShadow geometry={nodes.Brada.geometry} material={materials.CLAY_Telo} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path001.geometry} material={materials.CLAY_Telo} position={[-0.053, 1.672, -0.133]} rotation={[-0.459, -1.35, -2.04]} scale={[0.035, 0.034, 0.034]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path002.geometry} material={materials.CLAY_Telo} position={[-0.042, 1.668, -0.126]} rotation={[-0.459, -1.35, -2.04]} scale={[0.039, 0.037, 0.037]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path003.geometry} material={materials.CLAY_Telo} position={[-0.027, 1.668, -0.113]} rotation={[-0.209, -1.124, -1.802]} scale={[0.045, 0.043, 0.043]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path004.geometry} material={materials.CLAY_Telo} position={[-0.012, 1.661, -0.11]} rotation={[-0.249, -1.187, -1.838]} scale={[0.039, 0.037, 0.037]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path005.geometry} material={materials.CLAY_Telo} position={[0.007, 1.659, -0.118]} rotation={[-0.249, -1.187, -1.838]} scale={[0.039, 0.037, 0.037]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path006.geometry} material={materials.CLAY_Telo} position={[0.031, 1.66, -0.13]} rotation={[-0.249, -1.187, -1.838]} scale={[0.028, 0.027, 0.027]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path007.geometry} material={materials.CLAY_Telo} position={[-0.059, 1.669, -0.143]} rotation={[1.813, -1.136, 0.504]} scale={[0.038, 0.037, 0.038]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path008.geometry} material={materials.CLAY_Telo} position={[-0.087, 1.665, -0.232]} rotation={[2.034, -1.091, 0.796]} scale={[0.038, 0.037, 0.038]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path009.geometry} material={materials.CLAY_Telo} position={[-0.089, 1.668, -0.221]} rotation={[2.095, -1.072, 0.869]} scale={[0.041, 0.04, 0.04]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path010.geometry} material={materials.CLAY_Telo} position={[-0.085, 1.672, -0.2]} rotation={[2.095, -1.072, 0.869]} scale={[0.041, 0.04, 0.04]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path011.geometry} material={materials.CLAY_Telo} position={[-0.084, 1.675, -0.177]} rotation={[1.864, -1.071, 0.654]} scale={[0.041, 0.04, 0.04]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path012.geometry} material={materials.CLAY_Telo} position={[-0.075, 1.673, -0.158]} rotation={[1.747, -1.119, 0.459]} scale={[0.041, 0.04, 0.04]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path013.geometry} material={materials.CLAY_Telo} position={[0.033, 1.689, -0.147]} rotation={[0.495, -1.122, 0.018]} scale={[0.037, 0.039, 0.037]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path014.geometry} material={materials.CLAY_Telo} position={[-0.088, 1.67, -0.253]} rotation={[2.214, -1.258, 1.071]} scale={[0.039, 0.037, 0.037]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path015.geometry} material={materials.CLAY_Telo} position={[-0.085, 1.663, -0.271]} rotation={[2.214, -1.258, 1.071]} scale={[0.039, 0.037, 0.037]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path017.geometry} material={materials.CLAY_Telo} position={[0.056, 1.662, -0.198]} rotation={[0.008, 0.076, -1.67]} scale={[0.035, 0.034, 0.034]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path018.geometry} material={materials.CLAY_Telo} position={[0.034, 1.671, -0.255]} rotation={[0.008, 0.076, -1.67]} scale={[0.035, 0.034, 0.034]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path019.geometry} material={materials.CLAY_Telo} position={[0.044, 1.673, -0.229]} rotation={[0.008, 0.076, -1.67]} scale={[0.035, 0.034, 0.034]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path020.geometry} material={materials.CLAY_Telo} position={[0.061, 1.632, -0.193]} rotation={[0.008, 0.076, -1.67]} scale={[0.035, 0.034, 0.034]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path021.geometry} material={materials.CLAY_Telo} position={[0.017, 1.665, -0.284]} rotation={[0.008, 0.076, -1.67]} scale={[0.035, 0.034, 0.034]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path022.geometry} material={materials.CLAY_Telo} position={[-0.073, 1.664, -0.285]} rotation={[1.901, 1.402, 2.574]} scale={[0.035, 0.034, 0.034]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path023.geometry} material={materials.CLAY_Telo} position={[-0.093, 1.666, -0.252]} rotation={[1.901, 1.402, 2.574]} scale={[0.035, 0.034, 0.034]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path024.geometry} material={materials.CLAY_Telo} position={[-0.101, 1.674, -0.223]} rotation={[1.901, 1.402, 2.574]} scale={[0.035, 0.034, 0.034]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path025.geometry} material={materials.CLAY_Telo} position={[-0.099, 1.678, -0.192]} rotation={[1.901, 1.402, 2.574]} scale={[0.026, 0.025, 0.025]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path026.geometry} material={materials.CLAY_Telo} position={[-0.09, 1.678, -0.164]} rotation={[1.901, 1.402, 2.574]} scale={[0.026, 0.025, 0.025]} />
      <mesh castShadow receiveShadow geometry={nodes.Hair_Path027.geometry} material={materials.CLAY_Telo} position={[-0.079, 1.676, -0.145]} rotation={[1.901, 1.402, 2.574]} scale={[0.026, 0.025, 0.025]} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path002.geometry} material={materials.CLAY_Telo} position={[-0.024, 1.607, -0.094]} rotation={[-1.299, -0.548, -3.089]} scale={[0.004, 0.004, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path003.geometry} material={materials.CLAY_Telo} position={[-0.05, 1.609, -0.097]} rotation={[1.38, -0.81, -0.287]} scale={0.004} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path004.geometry} material={materials.CLAY_Telo} position={[-0.041, 1.608, -0.093]} rotation={[0.517, -1.232, -1.234]} scale={0.004} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path005.geometry} material={materials.CLAY_Telo} position={[-0.028, 1.607, -0.093]} rotation={[-0.536, -1.216, -2.366]} scale={0.004} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path006.geometry} material={materials.CLAY_Telo} position={[-0.032, 1.608, -0.092]} rotation={[-1.278, -0.687, -3.069]} scale={0.003} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path007.geometry} material={materials.CLAY_Telo} position={[0.013, 1.604, -0.101]} rotation={[1.842, 0.548, -0.052]} scale={[0.004, 0.004, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path008.geometry} material={materials.CLAY_Telo} position={[0.035, 1.602, -0.114]} rotation={[-1.762, 0.81, -2.854]} scale={0.004} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path009.geometry} material={materials.CLAY_Telo} position={[0.028, 1.607, -0.107]} rotation={[-2.624, 1.232, -1.907]} scale={0.004} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path010.geometry} material={materials.CLAY_Telo} position={[0.02, 1.602, -0.103]} rotation={[1.864, 0.687, -0.073]} scale={0.003} />
      <mesh castShadow receiveShadow geometry={nodes.Eyebrows_Path011.geometry} material={materials.CLAY_Telo} position={[0.037, 1.606, -0.113]} rotation={[-2.624, 1.232, -1.907]} scale={0.002} />
      <mesh castShadow receiveShadow geometry={nodes.Telo_bez_hlavy.geometry} material={materials.CLAY_Telo} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.955]} />
    </group>
  )
}

useGLTF.preload('/Self-character-compressed.glb')
