name: Build and deploy website to server on push
on:
    push:
        branches: ["production"]

jobs:
    build:
        name: Build 🔨
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Build dependencies
              run: npm run build
            - name: Copy .htaccess file to fix routing on Apache server
              run: |
                  FILENAME=.htaccess
                  cp "./server-config/$FILENAME" "./dist/$FILENAME"
                  echo "$FILENAME file copied to production dist folder"

                  cd dist
                  echo "All Files in production dist folder:"
                  ls -la
                  cd ../
            - name: Archive production artifact
              uses: actions/upload-artifact@main
              with:
                  name: dist
                  path: dist
    deploy:
        name: Deploy 🚀
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Download artifact
              uses: actions/download-artifact@main
              with:
                  name: dist
                  path: dist
            - name: 📂 Sync files to hosting
              uses: SamKirkland/web-deploy@v1
              with:
                  target-server: ${{ secrets.HOSTING_SSH_HOST }}
                  remote-user: ${{ secrets.HOSTING_SSH_USER_LOGIN }}
                  private-ssh-key: ${{ secrets.HOSTING_SSH_PRIVATE_KEY }}
                  ssh-port: ${{ secrets.HOSTING_SSH_PORT }}
                  source-path: ./dist/
                  destination-path: ~/michalbeno.eu/web/
                  rsync-options: --archive --verbose --compress --human-readable --stats
